name: quip_node_ffi
description: FFI bindings for the QUIP node.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.13.0
  freezed_annotation: ^3.1.0
dev_dependencies:
  build_runner: ^2.14.0
  freezed: ^3.2.5
